export const PRODUCT_LIST_REQUSET = 'PRODUCT_LIST_REQUSET'; 
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'; 
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'; 




export const PRODUCT_DETAILS_REQUSET = 'PRODUCT_DETAILS_REQUSET'; 
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'; 
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'; 